### ISSUE TITLE
Error: Cannot use simple-git on a directory that does not exist

### ISSUE THREAD

**Issue by Leeft** [paul-schaaf/talon-filetree#9]
I'm on Windows 10, and see this error with the latest on both VSCode and VSCode Insiders.

Thought initially it was only because I wasn't using a git directory yet for my project (Arduino sketch, one folder in the workspace), but it does it on anything.

```
Error: Cannot use simple-git on a directory that does not exist
	at gitInstanceFactory (c:\Users\lianna\.vscode\extensions\paulschaaf.talon-filetree-0.5.9\node_modules\simple-git\dist\cjs\index.js:4018:11)
	at FileSystemProvider.isIgnored (c:\Users\lianna\.vscode\extensions\paulschaaf.talon-filetree-0.5.9\out\fileExplorer.js:72:57)
	at FileSystemProvider.getChildren (c:\Users\lianna\.vscode\extensions\paulschaaf.talon-filetree-0.5.9\out\fileExplorer.js:153:49)
	at async w.R (c:\Users\lianna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:66288)
	at async w.getChildren (c:\Users\lianna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:62707)
c @ notificationsAlerts.ts:40
```

**Comment by Leeft** [comment]
Appears good now on the latest version, thank you @paul-schaaf
